"""nana.social — social draft, classification, and guard subsystem."""

# classifier
from nana.social.classifier import (
    social_source_classification,
    build_social_draft_source,
    detect_public_reaction_style,
    social_vibe_topic_style_override,
    detect_social_media_mode,
    source_match_bundle,
    strip_accents_for_match,
    extract_social_title_content,
    extract_labeled_match_text,
    primary_social_context_match_text,
    visible_post_match_text,
    vision_match_text,
    # source_has_* detectors
    source_has_cute_context,
    source_has_conflict_context,
    source_has_crime_violence_context,
    source_has_harassment_boundary_context,
    source_has_minor_safety_context,
    source_has_self_harm_sensitive_context,
    source_has_sexual_sensitive_context,
    source_has_serious_issue_context,
    source_has_financial_scam_context,
    source_has_legal_sensitive_context,
    source_has_misinfo_uncertain_context,
    source_has_public_safety_context,
    source_has_politics_sensitive_context,
    source_has_medical_sensitive_context,
    source_has_grief_sensitive_context,
    source_has_weather_funny_context,
    source_has_awkward_danger_context,
    source_has_disaster_emergency_context,
    source_has_accident_or_traffic_context,
    source_has_quick_reaction_context,
    source_has_space_launch_context,
    source_has_overloaded_ride_funny_context,
    source_has_animal_standoff_context,
    source_has_absurd_work_context,
    source_has_danger_context,
    source_has_school_memory_context,
    # danger helpers
    danger_context_should_not_praise_reaction,
    fallback_danger_public_reply,
    # guard matrix
    SOCIAL_GUARD_EXAMPLES,
    GENERIC_UNSAFE_FALLBACKS,
    SENSITIVE_DRAFT_STYLES,
    social_guard_expected_fallback_ok,
    social_guard_matrix_rows,
    social_guard_matrix_summary,
    DEFAULT_SOCIAL_CLASSIFY_REQUEST,
    is_diagnostic_fragment,
)

# draft
from nana.social.draft import (
    print_social_draft_test,
    find_recent_duplicate_draft,
    print_draft_queue,
    print_draft_show,
    print_draft_confirm,
    print_draft_cancel,
    print_draft_item,
    propose_social_type_draft,
    social_type_context_block_reason,
    choose_social_draft_models,
    social_request_has_clear_topic,
    social_request_needs_page_context,
    social_target_missing_reason,
    normalize_draft_duplicate_key,
    normalize_slashy_command_text,
    parse_int_arg,
    shorten_line,
)

# guards
from nana.social.guards import (
    fallback_social_draft,
    fallback_public_social_reply,
    soften_public_social_reply,
    enforce_short_public_reply,
    compact_public_reaction_reply,
    trim_public_social_reply,
    public_social_reply_seems_off_topic,
)

# quality
from nana.social.quality import (
    draft_quality_report,
    draft_quality_summary,
    print_draft_quality,
    print_draft_quality_test,
    social_draft_needs_fallback,
    polish_social_draft_quality,
    social_draft_has_obvious_quality_issue,
    sanitize_teo_lite_reply,
    remove_disallowed_social_draft_bits,
    is_diagnostic_fragment,
)

# prompts
from nana.social.prompts import (
    build_social_draft_prompt,
    enrich_social_context_packet,
    call_social_draft_with_fallbacks,
    clean_social_draft,
    social_draft_guard_note,
)

# teo_lite
from nana.social.teo_lite import (
    should_use_teo_lite,
    apply_teo_lite_public_reply,
)

__all__ = [
    # classifier
    "social_source_classification",
    "build_social_draft_source",
    "detect_public_reaction_style",
    "social_vibe_topic_style_override",
    "detect_social_media_mode",
    "source_match_bundle",
    "strip_accents_for_match",
    "extract_social_title_content",
    "extract_labeled_match_text",
    "primary_social_context_match_text",
    "visible_post_match_text",
    "vision_match_text",
    "source_has_cute_context",
    "source_has_conflict_context",
    "source_has_crime_violence_context",
    "source_has_harassment_boundary_context",
    "source_has_minor_safety_context",
    "source_has_self_harm_sensitive_context",
    "source_has_sexual_sensitive_context",
    "source_has_serious_issue_context",
    "source_has_financial_scam_context",
    "source_has_legal_sensitive_context",
    "source_has_misinfo_uncertain_context",
    "source_has_public_safety_context",
    "source_has_politics_sensitive_context",
    "source_has_medical_sensitive_context",
    "source_has_grief_sensitive_context",
    "source_has_weather_funny_context",
    "source_has_awkward_danger_context",
    "source_has_disaster_emergency_context",
    "source_has_accident_or_traffic_context",
    "source_has_quick_reaction_context",
    "source_has_space_launch_context",
    "source_has_overloaded_ride_funny_context",
    "source_has_animal_standoff_context",
    "source_has_absurd_work_context",
    "source_has_danger_context",
    "source_has_school_memory_context",
    "danger_context_should_not_praise_reaction",
    "fallback_danger_public_reply",
    "SOCIAL_GUARD_EXAMPLES",
    "GENERIC_UNSAFE_FALLBACKS",
    "SENSITIVE_DRAFT_STYLES",
    "social_guard_expected_fallback_ok",
    "social_guard_matrix_rows",
    "social_guard_matrix_summary",
    "DEFAULT_SOCIAL_CLASSIFY_REQUEST",
    "is_diagnostic_fragment",
    # draft
    "print_social_draft_test",
    "find_recent_duplicate_draft",
    "print_draft_queue",
    "print_draft_show",
    "print_draft_confirm",
    "print_draft_cancel",
    "print_draft_item",
    "propose_social_type_draft",
    "social_type_context_block_reason",
    "choose_social_draft_models",
    "social_request_has_clear_topic",
    "social_request_needs_page_context",
    "social_target_missing_reason",
    "normalize_draft_duplicate_key",
    "normalize_slashy_command_text",
    "parse_int_arg",
    "shorten_line",
    # guards
    "fallback_social_draft",
    "fallback_public_social_reply",
    "soften_public_social_reply",
    "enforce_short_public_reply",
    "compact_public_reaction_reply",
    "trim_public_social_reply",
    "public_social_reply_seems_off_topic",
    # quality
    "draft_quality_report",
    "draft_quality_summary",
    "print_draft_quality",
    "print_draft_quality_test",
    "social_draft_needs_fallback",
    "polish_social_draft_quality",
    "social_draft_has_obvious_quality_issue",
    "sanitize_teo_lite_reply",
    "remove_disallowed_social_draft_bits",
    # prompts
    "build_social_draft_prompt",
    "enrich_social_context_packet",
    "call_social_draft_with_fallbacks",
    "clean_social_draft",
    "social_draft_guard_note",
    # teo_lite
    "should_use_teo_lite",
    "apply_teo_lite_public_reply",
]
