"""Lightweight command index for core/live phase router.

Kept separate so the thin facade can reject unrelated slash commands without
importing the large phase router implementation.
"""

from __future__ import annotations

_CORE_PHASE_EXACT_COMMANDS = frozenset({
    '/action-contract',
    '/action-trace',
    '/action-trace-guard-status',
    '/anti-lore-status',
    '/anti-lore-test',
    '/attention',
    '/attention-memory-guard-status',
    '/attention-memory-status',
    '/attention-memory-test',
    '/attention-rhythm-guard-status',
    '/attention-rhythm-status',
    '/attention-rhythm-test',
    '/attention-state-guard-status',
    '/attention-state-status',
    '/attention-state-test',
    '/attention-status',
    '/audit-clear',
    '/audit-guard-status',
    '/audit-log',
    '/audit-replay',
    '/audit-review',
    '/autonomy-lock',
    '/bounded-pilot-guard-status',
    '/bounded-pilot-status',
    '/bounded-pilot-test',
    '/broker-guard-status',
    '/broker-matrix',
    '/clear-recovery',
    '/cns-gate-guard-status',
    '/cns-gate-status',
    '/cns-gate-test',
    '/cns-inventory',
    '/cns-map',
    '/command-normalize-test',
    '/command-route-test',
    '/command-route-truth-status',
    '/command-router-guard-status',
    '/command-router-status',
    '/command-truth',
    '/command-truth-status',
    '/companion-consistency-guard-status',
    '/companion-consistency-status',
    '/companion-consistency-test',
    '/companion-habit-status',
    '/companion-habit-test',
    '/companion-integration-guard-status',
    '/companion-integration-status',
    '/companion-integration-test',
    '/companion-live-guard-status',
    '/companion-live-status',
    '/companion-live-test',
    '/companion-response-guard-status',
    '/companion-response-status',
    '/companion-response-test',
    '/companion-safety-guard-status',
    '/companion-safety-status',
    '/companion-safety-test',
    '/continuity-candidate-status',
    '/continuity-candidate-test',
    '/conversation-rhythm-check',
    '/conversation-rhythm-guard-status',
    '/conversation-rhythm-status',
    '/conversation-rhythm-test',
    '/daily-frame-guard-status',
    '/daily-frame-status',
    '/daily-frame-test',
    '/daily-loop-guard-status',
    '/daily-loop-status',
    '/daily-loop-test',
    '/day-continuity-guard-status',
    '/day-continuity-status',
    '/day-continuity-test',
    '/dialogue-drift-check',
    '/dialogue-drift-guard-status',
    '/dialogue-drift-status',
    '/dialogue-drift-test',
    '/dialogue-energy-guard-status',
    '/dialogue-energy-status',
    '/dialogue-energy-test',
    '/dialogue-gate-guard-status',
    '/dialogue-gate-status',
    '/dialogue-gate-test',
    '/dry-run',
    '/dry-run-expect',
    '/dry-run-guard-status',
    '/dry-run-last',
    '/dry-run-quality',
    '/event-log',
    '/event-log-clear',
    '/event-store-guard-status',
    '/event-store-status',
    '/executor-rehearsal-guard-status',
    '/executor-rehearsal-status',
    '/executor-rehearsal-test',
    '/grounded-reflection-guard-status',
    '/grounded-reflection-status',
    '/grounded-reflection-test',
    '/habit-candidate-guard-status',
    '/habit-candidate-status',
    '/habit-candidate-test',
    '/kill-switch-status',
    '/kill-switch-test',
    '/long-session-status',
    '/memory-conflict-guard-status',
    '/memory-conflict-status',
    '/memory-conflict-test',
    '/memory-decay-guard-status',
    '/memory-decay-status',
    '/memory-decay-test',
    '/memory-gate-guard-status',
    '/memory-gate-status',
    '/memory-gate-test',
    '/memory-governance-guard-status',
    '/memory-governance-status',
    '/memory-governance-test',
    '/memory-v3-guard-status',
    '/memory-v3-status',
    '/memory-v3-test',
    '/nana-boundary-guard-status',
    '/nana-boundary-status',
    '/nana-boundary-test',
    '/nana-level5-map',
    '/nana-policy-map-guard-status',
    '/nana-policy-map-status',
    '/nana-policy-map-test',
    '/nana-priority-guard-status',
    '/nana-priority-status',
    '/nana-priority-test',
    '/nana-runtime-state-guard-status',
    '/nana-runtime-state-status',
    '/nana-runtime-state-test',
    '/nana-stream-guard-status',
    '/nana-stream-status',
    '/nana-stream-test',
    '/output-candidate-guard-status',
    '/output-candidate-status',
    '/output-candidate-test',
    '/output-gate-guard-status',
    '/output-gate-status',
    '/output-gate-test',
    '/p10',
    '/p10-1',
    '/p10-1-ready',
    '/p10-10',
    '/p10-10-ready',
    '/p10-2',
    '/p10-2-ready',
    '/p10-3',
    '/p10-3-ready',
    '/p10-4',
    '/p10-4-ready',
    '/p10-5',
    '/p10-5-ready',
    '/p10-6',
    '/p10-6-ready',
    '/p10-7',
    '/p10-7-ready',
    '/p10-8',
    '/p10-8-ready',
    '/p10-9',
    '/p10-9-ready',
    '/p10-ready',
    '/p11',
    '/p11-1',
    '/p11-1-ready',
    '/p11-10',
    '/p11-10-ready',
    '/p11-2',
    '/p11-2-ready',
    '/p11-3',
    '/p11-3-ready',
    '/p11-4',
    '/p11-4-ready',
    '/p11-5',
    '/p11-5-ready',
    '/p11-6',
    '/p11-6-ready',
    '/p11-7',
    '/p11-7-ready',
    '/p11-8',
    '/p11-8-ready',
    '/p11-9',
    '/p11-9-ready',
    '/p11-ready',
    '/p12',
    '/p12-1',
    '/p12-1-ready',
    '/p12-2',
    '/p12-2-ready',
    '/p12-3',
    '/p12-3-ready',
    '/p12-4',
    '/p12-4-ready',
    '/p12-5',
    '/p12-5-ready',
    '/p12-ready',
    '/p13',
    '/p13-1',
    '/p13-1-ready',
    '/p13-2',
    '/p13-2-ready',
    '/p13-3',
    '/p13-3-ready',
    '/p13-4',
    '/p13-4-ready',
    '/p13-5',
    '/p13-5-ready',
    '/p13-ready',
    '/p14',
    '/p14-1',
    '/p14-1-ready',
    '/p14-2',
    '/p14-2-ready',
    '/p14-3',
    '/p14-3-ready',
    '/p14-4',
    '/p14-4-ready',
    '/p14-5',
    '/p14-5-ready',
    '/p14-ready',
    '/p15',
    '/p15-1',
    '/p15-1-ready',
    '/p15-2',
    '/p15-2-ready',
    '/p15-3',
    '/p15-3-ready',
    '/p15-4',
    '/p15-4-ready',
    '/p15-5',
    '/p15-5-ready',
    '/p15-ready',
    '/p16',
    '/p16-1',
    '/p16-1-ready',
    '/p16-2',
    '/p16-2-ready',
    '/p16-3',
    '/p16-3-ready',
    '/p16-4',
    '/p16-4-ready',
    '/p16-5',
    '/p16-5-ready',
    '/p16-ready',
    '/p17',
    '/p17-1',
    '/p17-1-ready',
    '/p17-2',
    '/p17-2-ready',
    '/p17-3',
    '/p17-3-ready',
    '/p17-4',
    '/p17-4-ready',
    '/p17-ready',
    '/p18',
    '/p18-1',
    '/p18-1-ready',
    '/p18-2',
    '/p18-2-ready',
    '/p18-3',
    '/p18-3-ready',
    '/p18-4',
    '/p18-4-ready',
    '/p18-ready',
    '/p7',
    '/p7-ready',
    '/p8',
    '/p8-ready',
    '/p81',
    '/p81-ready',
    '/p82',
    '/p82-ready',
    '/p83',
    '/p83-ready',
    '/p84',
    '/p84-ready',
    '/p85',
    '/p85-ready',
    '/p9',
    '/p9-ready',
    '/permission-ledger-guard-status',
    '/permission-ledger-status',
    '/permission-ledger-test',
    '/persona-status',
    '/phase10-1-guard-status',
    '/phase10-1-ready',
    '/phase10-1-status',
    '/phase10-10-guard-status',
    '/phase10-10-ready',
    '/phase10-10-status',
    '/phase10-10-test',
    '/phase10-2-guard-status',
    '/phase10-2-ready',
    '/phase10-2-status',
    '/phase10-3-guard-status',
    '/phase10-3-ready',
    '/phase10-3-status',
    '/phase10-4-guard-status',
    '/phase10-4-ready',
    '/phase10-4-status',
    '/phase10-5-guard-status',
    '/phase10-5-ready',
    '/phase10-5-status',
    '/phase10-6-guard-status',
    '/phase10-6-ready',
    '/phase10-6-status',
    '/phase10-7-guard-status',
    '/phase10-7-ready',
    '/phase10-7-status',
    '/phase10-8-guard-status',
    '/phase10-8-ready',
    '/phase10-8-status',
    '/phase10-9-guard-status',
    '/phase10-9-ready',
    '/phase10-9-status',
    '/phase10-checklist',
    '/phase10-guard-status',
    '/phase10-ready',
    '/phase10-status',
    '/phase11-1-guard-status',
    '/phase11-1-ready',
    '/phase11-1-status',
    '/phase11-1-test',
    '/phase11-10-guard-status',
    '/phase11-10-ready',
    '/phase11-10-status',
    '/phase11-10-test',
    '/phase11-2-guard-status',
    '/phase11-2-ready',
    '/phase11-2-status',
    '/phase11-2-test',
    '/phase11-3-guard-status',
    '/phase11-3-ready',
    '/phase11-3-status',
    '/phase11-3-test',
    '/phase11-4-guard-status',
    '/phase11-4-ready',
    '/phase11-4-status',
    '/phase11-4-test',
    '/phase11-5-guard-status',
    '/phase11-5-ready',
    '/phase11-5-status',
    '/phase11-5-test',
    '/phase11-6-guard-status',
    '/phase11-6-ready',
    '/phase11-6-status',
    '/phase11-6-test',
    '/phase11-7-guard-status',
    '/phase11-7-ready',
    '/phase11-7-status',
    '/phase11-7-test',
    '/phase11-8-guard-status',
    '/phase11-8-ready',
    '/phase11-8-status',
    '/phase11-8-test',
    '/phase11-9-guard-status',
    '/phase11-9-ready',
    '/phase11-9-status',
    '/phase11-9-test',
    '/phase11-gate-guard-status',
    '/phase11-gate-status',
    '/phase11-gate-test',
    '/phase11-ready',
    '/phase11-status',
    '/phase12-1-guard-status',
    '/phase12-1-ready',
    '/phase12-1-status',
    '/phase12-1-test',
    '/phase12-2-guard-status',
    '/phase12-2-ready',
    '/phase12-2-status',
    '/phase12-2-test',
    '/phase12-3-guard-status',
    '/phase12-3-ready',
    '/phase12-3-status',
    '/phase12-3-test',
    '/phase12-4-guard-status',
    '/phase12-4-ready',
    '/phase12-4-status',
    '/phase12-4-test',
    '/phase12-5-guard-status',
    '/phase12-5-ready',
    '/phase12-5-status',
    '/phase12-5-test',
    '/phase12-ready',
    '/phase12-status',
    '/phase13-1-guard-status',
    '/phase13-1-ready',
    '/phase13-1-status',
    '/phase13-1-test',
    '/phase13-2-guard-status',
    '/phase13-2-ready',
    '/phase13-2-status',
    '/phase13-2-test',
    '/phase13-3-guard-status',
    '/phase13-3-ready',
    '/phase13-3-status',
    '/phase13-3-test',
    '/phase13-4-guard-status',
    '/phase13-4-ready',
    '/phase13-4-status',
    '/phase13-4-test',
    '/phase13-5-guard-status',
    '/phase13-5-ready',
    '/phase13-5-status',
    '/phase13-5-test',
    '/phase13-ready',
    '/phase13-status',
    '/phase14-1-guard-status',
    '/phase14-1-ready',
    '/phase14-1-status',
    '/phase14-1-test',
    '/phase14-2-guard-status',
    '/phase14-2-ready',
    '/phase14-2-status',
    '/phase14-2-test',
    '/phase14-3-guard-status',
    '/phase14-3-ready',
    '/phase14-3-status',
    '/phase14-3-test',
    '/phase14-4-guard-status',
    '/phase14-4-ready',
    '/phase14-4-status',
    '/phase14-4-test',
    '/phase14-5-guard-status',
    '/phase14-5-ready',
    '/phase14-5-status',
    '/phase14-5-test',
    '/phase14-ready',
    '/phase14-status',
    '/phase15-1-guard-status',
    '/phase15-1-ready',
    '/phase15-1-status',
    '/phase15-1-test',
    '/phase15-2-guard-status',
    '/phase15-2-ready',
    '/phase15-2-status',
    '/phase15-2-test',
    '/phase15-3-guard-status',
    '/phase15-3-ready',
    '/phase15-3-status',
    '/phase15-3-test',
    '/phase15-4-guard-status',
    '/phase15-4-ready',
    '/phase15-4-status',
    '/phase15-4-test',
    '/phase15-5-guard-status',
    '/phase15-5-ready',
    '/phase15-5-status',
    '/phase15-5-test',
    '/phase15-ready',
    '/phase15-status',
    '/phase16-1-guard-status',
    '/phase16-1-ready',
    '/phase16-1-status',
    '/phase16-1-test',
    '/phase16-2-guard-status',
    '/phase16-2-ready',
    '/phase16-2-status',
    '/phase16-2-test',
    '/phase16-3-guard-status',
    '/phase16-3-ready',
    '/phase16-3-status',
    '/phase16-3-test',
    '/phase16-4-guard-status',
    '/phase16-4-ready',
    '/phase16-4-status',
    '/phase16-4-test',
    '/phase16-5-guard-status',
    '/phase16-5-ready',
    '/phase16-5-status',
    '/phase16-5-test',
    '/phase16-ready',
    '/phase16-status',
    '/phase17-1-guard-status',
    '/phase17-1-ready',
    '/phase17-1-status',
    '/phase17-1-test',
    '/phase17-2-guard-status',
    '/phase17-2-ready',
    '/phase17-2-status',
    '/phase17-2-test',
    '/phase17-3-guard-status',
    '/phase17-3-ready',
    '/phase17-3-status',
    '/phase17-3-test',
    '/phase17-4-guard-status',
    '/phase17-4-ready',
    '/phase17-4-status',
    '/phase17-4-test',
    '/phase17-ready',
    '/phase17-status',
    '/phase18-1-guard-status',
    '/phase18-1-ready',
    '/phase18-1-status',
    '/phase18-1-test',
    '/phase18-2-guard-status',
    '/phase18-2-ready',
    '/phase18-2-status',
    '/phase18-2-test',
    '/phase18-3-guard-status',
    '/phase18-3-ready',
    '/phase18-3-status',
    '/phase18-3-test',
    '/phase18-4-guard-status',
    '/phase18-4-ready',
    '/phase18-4-status',
    '/phase18-4-test',
    '/phase18-ready',
    '/phase18-status',
    '/phase7-dry-run',
    '/phase7-guard-status',
    '/phase7-log',
    '/phase7-pending',
    '/phase7-pending-guard-status',
    '/phase7-quality',
    '/phase7-ready',
    '/phase7-status',
    '/phase8-action-trace-guard-status',
    '/phase8-broker-matrix',
    '/phase8-guard-status',
    '/phase8-pre-exec',
    '/phase8-pre-exec-guard-status',
    '/phase8-ready',
    '/phase8-status',
    '/phase81-guard-status',
    '/phase81-ready',
    '/phase81-status',
    '/phase81-test',
    '/phase82-guard-status',
    '/phase82-ready',
    '/phase82-status',
    '/phase82-test',
    '/phase83-guard-status',
    '/phase83-ready',
    '/phase83-status',
    '/phase83-test',
    '/phase84-guard-status',
    '/phase84-ready',
    '/phase84-status',
    '/phase84-test',
    '/phase85-guard-status',
    '/phase85-ready',
    '/phase85-status',
    '/phase85-test',
    '/phase9-clear',
    '/phase9-guard-status',
    '/phase9-log',
    '/phase9-ready',
    '/phase9-replay',
    '/phase9-review',
    '/phase9-status',
    '/plan-cancel',
    '/plan-confirm',
    '/plan-guard-status',
    '/plan-log',
    '/plan-pending',
    '/plan-preview',
    '/plan-propose',
    '/pre-exec-check',
    '/pre-exec-guard-status',
    '/presence-entropy-guard-status',
    '/presence-entropy-status',
    '/presence-entropy-test',
    '/presence-gate-guard-status',
    '/presence-gate-status',
    '/presence-gate-test',
    '/presence-stability-guard-status',
    '/presence-stability-status',
    '/presence-stability-test',
    '/queue-core-guard-status',
    '/queue-core-status',
    '/recovery',
    '/recovery-clear',
    '/recovery-continuity-guard-status',
    '/recovery-continuity-status',
    '/recovery-continuity-test',
    '/recovery-governor-guard-status',
    '/recovery-governor-status',
    '/recovery-status',
    '/recovery-test',
    '/reflection-injection-guard-status',
    '/reflection-injection-status',
    '/reflection-injection-test',
    '/reflection-safety-guard-status',
    '/reflection-safety-status',
    '/reflection-safety-test',
    '/reflective-gate-guard-status',
    '/reflective-gate-status',
    '/reflective-gate-test',
    '/reflective-presence-status',
    '/reflective-state-guard-status',
    '/reflective-state-status',
    '/reflective-state-test',
    '/residue',
    '/residue-status',
    '/response-shape-guard-status',
    '/response-shape-status',
    '/response-shape-test',
    '/runtime-inventory',
    '/runtime-map',
    '/runtime-state-schema',
    '/runtime-stress-guard-status',
    '/runtime-stress-status',
    '/runtime-stress-test',
    '/sandbox-boundary-guard-status',
    '/sandbox-boundary-status',
    '/sandbox-boundary-test',
    '/scheduler-guard-status',
    '/scheduler-status',
    '/scheduler-test',
    '/session-atmosphere-status',
    '/session-atmosphere-test',
    '/session-review-guard-status',
    '/session-review-status',
    '/session-review-test',
    '/shared-experience-guard-status',
    '/shared-experience-status',
    '/shared-experience-test',
    '/shared-recall-guard-status',
    '/shared-recall-status',
    '/shared-recall-test',
    '/ship-checklist',
    '/silence-hold-guard-status',
    '/silence-hold-status',
    '/silence-hold-test',
    '/social-vision-decouple-guard-status',
    '/social-vision-decouple-status',
    '/social-vision-decouple-test',
    '/state-schema',
    '/state-schema-guard-status',
    '/target-lock-guard-status',
    '/target-lock-status',
    '/target-lock-test',
    '/trust-calibration-guard-status',
    '/trust-calibration-status',
    '/trust-calibration-test',
    '/vibe-status',
})

_CORE_PHASE_PREFIX_COMMANDS = (
    '/action-contract ',
    '/action-trace ',
    '/anti-lore-test ',
    '/attention-memory-test ',
    '/attention-rhythm-test ',
    '/attention-state-test ',
    '/audit-replay ',
    '/audit-review ',
    '/bounded-pilot-preview',
    '/bounded-pilot-test ',
    '/cns-gate-test ',
    '/command-normalize-test ',
    '/command-route-test ',
    '/command-truth ',
    '/companion-consistency-test ',
    '/companion-habit-test ',
    '/companion-integration-test ',
    '/companion-live-test ',
    '/companion-response-preview',
    '/companion-response-test ',
    '/companion-safety-check',
    '/companion-safety-test ',
    '/continuity-candidate-test ',
    '/conversation-rhythm-check ',
    '/conversation-rhythm-test ',
    '/daily-frame-test ',
    '/daily-loop-test ',
    '/day-continuity-test ',
    '/dialogue-drift-check ',
    '/dialogue-drift-test ',
    '/dialogue-energy-test ',
    '/dialogue-gate-test ',
    '/dry-run ',
    '/dry-run-expect ',
    '/dry-run-quality ',
    '/dry-run-show',
    '/event-replay',
    '/executor-rehearsal-test ',
    '/grounded-reflection-test ',
    '/habit-candidate-test ',
    '/kill-switch-test ',
    '/memory-conflict-test ',
    '/memory-decay-test ',
    '/memory-gate-test ',
    '/memory-governance-test ',
    '/memory-v3-test ',
    '/nana-boundary-test ',
    '/nana-policy-map-test ',
    '/nana-priority-test ',
    '/nana-runtime-state-test ',
    '/nana-stream-mode',
    '/nana-stream-test ',
    '/output-candidate-preview',
    '/output-candidate-test ',
    '/output-gate-test ',
    '/permission-ledger-row',
    '/permission-ledger-test ',
    '/phase10-10-test ',
    '/phase11-1-test ',
    '/phase11-10-test ',
    '/phase11-2-test ',
    '/phase11-3-test ',
    '/phase11-4-test ',
    '/phase11-5-test ',
    '/phase11-6-test ',
    '/phase11-7-test ',
    '/phase11-8-test ',
    '/phase11-9-test ',
    '/phase11-gate-test ',
    '/phase12-1-test ',
    '/phase12-2-test ',
    '/phase12-3-test ',
    '/phase12-4-test ',
    '/phase12-5-test ',
    '/phase13-1-test ',
    '/phase13-2-test ',
    '/phase13-3-test ',
    '/phase13-4-test ',
    '/phase13-5-test ',
    '/phase14-1-test ',
    '/phase14-2-test ',
    '/phase14-3-test ',
    '/phase14-4-test ',
    '/phase14-5-test ',
    '/phase15-1-test ',
    '/phase15-2-test ',
    '/phase15-3-test ',
    '/phase15-4-test ',
    '/phase15-5-test ',
    '/phase16-1-test ',
    '/phase16-2-test ',
    '/phase16-3-test ',
    '/phase16-4-test ',
    '/phase16-5-test ',
    '/phase17-1-test ',
    '/phase17-2-test ',
    '/phase17-3-test ',
    '/phase17-4-test ',
    '/phase18-1-test ',
    '/phase18-2-test ',
    '/phase18-3-test ',
    '/phase18-4-test ',
    '/phase7-dry-run ',
    '/phase7-quality ',
    '/phase8-pre-exec ',
    '/phase81-test ',
    '/phase82-test ',
    '/phase83-test ',
    '/phase84-test ',
    '/phase85-test ',
    '/phase9-replay ',
    '/phase9-review ',
    '/plan-cancel ',
    '/plan-confirm ',
    '/plan-preview ',
    '/plan-propose ',
    '/pre-exec-check ',
    '/presence-entropy-test ',
    '/presence-gate-test ',
    '/presence-stability-test ',
    '/recovery-continuity-test ',
    '/recovery-test ',
    '/reflection-injection-preview',
    '/reflection-injection-test ',
    '/reflection-safety-check',
    '/reflection-safety-test ',
    '/reflective-gate-test ',
    '/reflective-state-test ',
    '/response-shape-test ',
    '/runtime-stress-test ',
    '/sandbox-boundary-test ',
    '/scheduler-test ',
    '/session-atmosphere-test ',
    '/session-review-preview',
    '/session-review-test ',
    '/shared-experience-test ',
    '/shared-recall-preview',
    '/shared-recall-test ',
    '/silence-hold-preview',
    '/silence-hold-test ',
    '/social-vision-decouple-test ',
    '/target-lock-test ',
    '/trust-calibration-test ',
)


def _is_core_phase_command(text_lower: str) -> bool:
    return text_lower in _CORE_PHASE_EXACT_COMMANDS or any(
        text_lower.startswith(prefix) for prefix in _CORE_PHASE_PREFIX_COMMANDS
    )


is_core_phase_command = _is_core_phase_command

__all__ = ["is_core_phase_command"]
