"""Fail-closed shells for archived legacy phase/voice commands.

The new runtime keeps these old slash-command names from crashing, but it does
not resurrect the old voice telemetry stack or import the monolithic main.py.
"""
from __future__ import annotations

from nana.commands.router_manifest import RUNTIME_HOT_PATH, archived_handler_reason


ARCHIVED_COMMAND_NAMES = (
    "print_controlled_stream_gate_guard_status",
    "print_controlled_stream_gate_status",
    "print_controlled_stream_gate_test",
    "print_controlled_stream_pilot_guard_status",
    "print_controlled_stream_pilot_test",
    "print_direct_voice_pilot_guard_status",
    "print_direct_voice_pilot_test",
    "print_final_phase_guard_status",
    "print_final_phase_ready",
    "print_final_phase_status",
    "print_final_phase_test",
    "print_guarded_stream_call_guard_status",
    "print_guarded_stream_call_test",
    "print_guarded_voice_dispatch_guard_status",
    "print_guarded_voice_dispatch_test",
    "print_live_path_replacement_guard_status",
    "print_live_path_replacement_status",
    "print_live_path_replacement_test",
    "print_live_stream_measurement_guard_status",
    "print_live_stream_measurement_status",
    "print_live_stream_measurement_test",
    "print_live_voice_control_guard_status",
    "print_live_voice_control_status",
    "print_live_voice_control_test",
    "print_live_voice_gate_guard_status",
    "print_live_voice_gate_status",
    "print_live_voice_gate_test",
    "print_stream_pilot_control_guard_status",
    "print_stream_pilot_control_status",
    "print_stream_pilot_control_test",
    "print_stream_pilot_enable_guard_status",
    "print_stream_pilot_enable_status",
    "print_stream_pilot_enable_test",
    "print_stream_rollback_guard_status",
    "print_stream_rollback_test",
    "print_voice_engine_impl_guard_status",
    "print_voice_engine_impl_status",
    "print_voice_engine_impl_test",
    "print_voice_engine_patch_guard_status",
    "print_voice_engine_patch_status",
    "print_voice_engine_patch_test",
    "print_voice_latency_baseline_guard_status",
    "print_voice_latency_baseline_status",
    "print_voice_latency_baseline_test",
    "print_voice_latency_design_guard_status",
    "print_voice_latency_design_status",
    "print_voice_latency_design_test",
    "print_voice_latency_gate_guard_status",
    "print_voice_latency_gate_status",
    "print_voice_latency_gate_test",
    "print_voice_stream_gate_guard_status",
    "print_voice_stream_gate_status",
    "print_voice_stream_gate_test",
    "print_voice_stream_safety_guard_status",
    "print_voice_stream_safety_status",
    "print_voice_stream_safety_test",
    "print_voice_streaming_decision_guard_status",
    "print_voice_streaming_decision_status",
    "print_voice_streaming_decision_test",
    "print_voice_streaming_dry_run_guard_status",
    "print_voice_streaming_dry_run_status",
    "print_voice_streaming_dry_run_test",
    "print_voice_telemetry_guard_status",
    "print_voice_telemetry_status",
    "print_voice_telemetry_test",
)


ADDITIONAL_ARCHIVED_COMMAND_NAMES = (
    "print_controlled_stream_pilot_status",
    "print_dialogue_gate_guard_status",
    "print_dialogue_gate_test",
    "print_expression_dispatch_guard_status",
    "print_expression_dispatch_status",
    "print_expression_dispatch_test",
    "print_guarded_stream_call_status",
    "print_live_reply_gate_guard_status",
    "print_live_reply_gate_status",
    "print_live_reply_gate_test",
    "print_live_reply_guard_status",
    "print_live_reply_status",
    "print_live_reply_test",
    "print_live_speech_safety_guard_status",
    "print_live_speech_safety_status",
    "print_live_speech_safety_test",
    "print_memory_gate_guard_status",
    "print_memory_gate_test",
    "print_output_gate_guard_status",
    "print_output_gate_test",
    "print_phase5_status",
    "print_phase6_ready",
    "print_phase6_status",
    "print_phase10_10_status",
    "print_phase10_1_status",
    "print_phase10_2_status",
    "print_phase10_3_status",
    "print_phase10_4_status",
    "print_phase10_5_status",
    "print_phase10_6_status",
    "print_phase10_7_status",
    "print_phase10_8_status",
    "print_phase10_9_status",
    "print_phase11_10_status",
    "print_phase11_1_status",
    "print_phase11_2_ready",
    "print_phase11_2_status",
    "print_phase11_3_status",
    "print_phase11_4_status",
    "print_phase11_5_status",
    "print_phase11_6_status",
    "print_phase11_7_status",
    "print_phase11_8_status",
    "print_phase11_9_status",
    "print_phase12_1_status",
    "print_phase12_2_status",
    "print_phase12_3_status",
    "print_phase12_4_status",
    "print_phase13_1_status",
    "print_phase13_2_status",
    "print_phase13_3_status",
    "print_phase13_4_status",
    "print_phase14_1_status",
    "print_phase14_2_status",
    "print_phase14_3_status",
    "print_phase14_4_status",
    "print_phase15_1_status",
    "print_phase15_2_status",
    "print_phase15_3_status",
    "print_phase15_4_status",
    "print_phase15_5_status",
    "print_phase16_1_status",
    "print_phase16_2_status",
    "print_phase16_3_status",
    "print_phase16_4_status",
    "print_phase17_1_status",
    "print_phase17_2_status",
    "print_phase17_3_status",
    "print_phase18_1_status",
    "print_phase18_2_status",
    "print_phase18_3_status",
    "print_phase18_4_status",
    "print_phase19_1_status",
    "print_phase19_2_status",
    "print_phase19_3_status",
    "print_phase19_4_status",
    "print_phase20_1_status",
    "print_phase20_2_status",
    "print_phase20_3_status",
    "print_phase20_4_status",
    "print_phase21_1_status",
    "print_phase21_2_status",
    "print_phase21_3_status",
    "print_phase21_4_status",
    "print_phase22_1_ready",
    "print_phase22_2_ready",
    "print_phase22_3_ready",
    "print_phase22_4_ready",
    "print_phase23_1_ready",
    "print_phase23_2_ready",
    "print_phase23_3_ready",
    "print_phase23_4_ready",
    "print_phase24_1_ready",
    "print_phase24_2_ready",
    "print_phase24_3_ready",
    "print_phase24_4_ready",
    "print_phase25_1_ready",
    "print_phase25_2_ready",
    "print_presence_gate_guard_status",
    "print_presence_gate_test",
    "print_reflective_gate_guard_status",
    "print_reflective_gate_test",
    "print_reply_bridge_guard_status",
    "print_reply_bridge_status",
    "print_reply_bridge_test",
    "print_reply_cooldown_guard_status",
    "print_reply_cooldown_status",
    "print_reply_cooldown_test",
    "print_runtime_state_schema",
    "print_speech_dispatch_guard_status",
    "print_speech_dispatch_status",
    "print_speech_dispatch_test",
    "print_state_schema_guard_status",
    "print_stream_rollback_status",
    "print_voice_binding_guard_status",
    "print_voice_binding_status",
    "print_voice_binding_test",
    "print_voice_dispatch_guard_status",
    "print_voice_dispatch_status",
    "print_voice_dispatch_test",
    "print_voice_gate_guard_status",
    "print_voice_gate_test",
)


LIVE_UNARCHIVED_COMMAND_NAMES = frozenset({
    "print_dialogue_gate_guard_status",
    "print_dialogue_gate_test",
    "print_expression_dispatch_guard_status",
    "print_expression_dispatch_status",
    "print_expression_dispatch_test",
    "print_live_reply_gate_guard_status",
    "print_live_reply_gate_status",
    "print_live_reply_gate_test",
    "print_live_reply_guard_status",
    "print_live_reply_status",
    "print_live_reply_test",
    "print_live_speech_safety_guard_status",
    "print_live_speech_safety_status",
    "print_live_speech_safety_test",
    "print_memory_gate_guard_status",
    "print_memory_gate_test",
    "print_output_gate_guard_status",
    "print_output_gate_test",
    "print_phase10_10_status",
    "print_phase10_1_status",
    "print_phase10_2_status",
    "print_phase10_3_status",
    "print_phase10_4_status",
    "print_phase10_5_status",
    "print_phase10_6_status",
    "print_phase10_7_status",
    "print_phase10_8_status",
    "print_phase10_9_status",
    "print_phase11_10_status",
    "print_phase11_1_status",
    "print_phase11_2_ready",
    "print_phase11_2_status",
    "print_phase11_3_status",
    "print_phase11_4_status",
    "print_phase11_5_status",
    "print_phase11_6_status",
    "print_phase11_7_status",
    "print_phase11_8_status",
    "print_phase11_9_status",
    "print_phase12_1_status",
    "print_phase12_2_status",
    "print_phase12_3_status",
    "print_phase12_4_status",
    "print_phase13_1_status",
    "print_phase13_2_status",
    "print_phase13_3_status",
    "print_phase13_4_status",
    "print_phase14_1_status",
    "print_phase14_2_status",
    "print_phase14_3_status",
    "print_phase14_4_status",
    "print_phase15_1_status",
    "print_phase15_2_status",
    "print_phase15_3_status",
    "print_phase15_4_status",
    "print_phase15_5_status",
    "print_phase16_1_status",
    "print_phase16_2_status",
    "print_phase16_3_status",
    "print_phase16_4_status",
    "print_phase17_1_status",
    "print_phase17_2_status",
    "print_phase17_3_status",
    "print_phase18_1_status",
    "print_phase18_2_status",
    "print_phase18_3_status",
    "print_phase18_4_status",
    "print_phase19_1_status",
    "print_phase19_2_status",
    "print_phase19_3_status",
    "print_phase19_4_status",
    "print_phase20_1_status",
    "print_phase20_2_status",
    "print_phase20_3_status",
    "print_phase20_4_status",
    "print_presence_gate_guard_status",
    "print_presence_gate_test",
    "print_reflective_gate_guard_status",
    "print_reflective_gate_test",
    "print_reply_bridge_guard_status",
    "print_reply_bridge_status",
    "print_reply_bridge_test",
    "print_reply_cooldown_guard_status",
    "print_reply_cooldown_status",
    "print_reply_cooldown_test",
    "print_runtime_state_schema",
    "print_speech_dispatch_guard_status",
    "print_speech_dispatch_status",
    "print_speech_dispatch_test",
    "print_state_schema_guard_status",
    "print_voice_binding_guard_status",
    "print_voice_binding_status",
    "print_voice_binding_test",
    "print_voice_dispatch_guard_status",
    "print_voice_dispatch_status",
    "print_voice_dispatch_test",
    "print_voice_gate_guard_status",
    "print_voice_gate_test",
})


def print_archived_command(name, *args, **_kwargs):
    phase = _extract_phase(args)
    reason, replacement = archived_handler_reason(name, phase)
    print("🗄️ Archived legacy command")
    print(f"  Handler: {name}")
    if phase is not None:
        print(f"  Phase: {phase}")
    print("  Status: archived_in_new_runtime")
    print(f"  Reason: {reason}")
    print(f"  Replacement: {replacement}")
    print(f"  Hot path: {RUNTIME_HOT_PATH}")
    print("  Safety: no live input, no TTS/VTS call, no legacy main import.")


def _extract_phase(args):
    if not args:
        return None
    first = args[0]
    if isinstance(first, (int, float, str)) and str(first).strip().isdigit():
        return str(first).strip()
    return None


def _archived(name):
    def _printer(*args, **kwargs):
        return print_archived_command(name, *args, **kwargs)

    _printer.__name__ = name
    return _printer


_ALL_ARCHIVED_COMMAND_NAMES = tuple(
    name
    for name in ARCHIVED_COMMAND_NAMES + ADDITIONAL_ARCHIVED_COMMAND_NAMES
    if name not in LIVE_UNARCHIVED_COMMAND_NAMES
)

globals().update({name: _archived(name) for name in _ALL_ARCHIVED_COMMAND_NAMES})

__all__ = (
    "ARCHIVED_COMMAND_NAMES",
    "ADDITIONAL_ARCHIVED_COMMAND_NAMES",
    "LIVE_UNARCHIVED_COMMAND_NAMES",
    "print_archived_command",
    *_ALL_ARCHIVED_COMMAND_NAMES,
)
