"""Lightweight command index for phase compatibility router."""

from __future__ import annotations

_PHASE_COMPAT_EXACT_COMMANDS = frozenset({
    '/controlled-stream-gate-guard-status',
    '/controlled-stream-gate-status',
    '/controlled-stream-gate-test',
    '/controlled-stream-pilot-guard-status',
    '/controlled-stream-pilot-status',
    '/controlled-stream-pilot-test',
    '/direct-voice-pilot-guard-status',
    '/direct-voice-pilot-status',
    '/direct-voice-pilot-test',
    '/expression-dispatch-guard-status',
    '/expression-dispatch-status',
    '/expression-dispatch-test',
    '/guarded-stream-call-guard-status',
    '/guarded-stream-call-status',
    '/guarded-stream-call-test',
    '/guarded-voice-dispatch-guard-status',
    '/guarded-voice-dispatch-status',
    '/guarded-voice-dispatch-test',
    '/live-path-replacement-guard-status',
    '/live-path-replacement-status',
    '/live-path-replacement-test',
    '/live-reply-gate-guard-status',
    '/live-reply-gate-status',
    '/live-reply-gate-test',
    '/live-reply-guard-status',
    '/live-reply-status',
    '/live-reply-test',
    '/live-speech-safety-guard-status',
    '/live-speech-safety-status',
    '/live-speech-safety-test',
    '/live-stream-measurement-guard-status',
    '/live-stream-measurement-status',
    '/live-stream-measurement-test',
    '/live-voice-control-guard-status',
    '/live-voice-control-status',
    '/live-voice-control-test',
    '/live-voice-gate-guard-status',
    '/live-voice-gate-status',
    '/live-voice-gate-test',
    '/p',
    '/p19',
    '/p19-1',
    '/p19-1-ready',
    '/p19-2',
    '/p19-2-ready',
    '/p19-3',
    '/p19-3-ready',
    '/p19-4',
    '/p19-4-ready',
    '/p19-5',
    '/p19-5-ready',
    '/p19-ready',
    '/p20',
    '/p20-1',
    '/p20-1-ready',
    '/p20-2',
    '/p20-2-ready',
    '/p20-3',
    '/p20-3-ready',
    '/p20-4',
    '/p20-4-ready',
    '/p20-5',
    '/p20-5-ready',
    '/p20-ready',
    '/p21',
    '/p21-1',
    '/p21-1-ready',
    '/p21-2',
    '/p21-2-ready',
    '/p21-3',
    '/p21-3-ready',
    '/p21-4',
    '/p21-4-ready',
    '/p21-5',
    '/p21-5-ready',
    '/p21-ready',
    '/p22',
    '/p22-1',
    '/p22-1-ready',
    '/p22-2',
    '/p22-2-ready',
    '/p22-3',
    '/p22-3-ready',
    '/p22-4',
    '/p22-4-ready',
    '/p22-5',
    '/p22-5-ready',
    '/p22-ready',
    '/p23',
    '/p23-1',
    '/p23-1-ready',
    '/p23-2',
    '/p23-2-ready',
    '/p23-3',
    '/p23-3-ready',
    '/p23-4',
    '/p23-4-ready',
    '/p23-5',
    '/p23-5-ready',
    '/p23-ready',
    '/p24',
    '/p24-1',
    '/p24-1-ready',
    '/p24-2',
    '/p24-2-ready',
    '/p24-3',
    '/p24-3-ready',
    '/p24-4',
    '/p24-4-ready',
    '/p24-5',
    '/p24-5-ready',
    '/p24-ready',
    '/p25-1',
    '/p25-1-ready',
    '/p25-2',
    '/p25-2-ready',
    '/p5',
    '/p6',
    '/p6-ready',
    '/phase',
    '/phase19-1-guard-status',
    '/phase19-1-ready',
    '/phase19-1-status',
    '/phase19-1-test',
    '/phase19-2-guard-status',
    '/phase19-2-ready',
    '/phase19-2-status',
    '/phase19-2-test',
    '/phase19-3-guard-status',
    '/phase19-3-ready',
    '/phase19-3-status',
    '/phase19-3-test',
    '/phase19-4-guard-status',
    '/phase19-4-ready',
    '/phase19-4-status',
    '/phase19-4-test',
    '/phase19-5-guard-status',
    '/phase19-5-ready',
    '/phase19-5-status',
    '/phase19-5-test',
    '/phase19-ready',
    '/phase19-status',
    '/phase20-1-guard-status',
    '/phase20-1-ready',
    '/phase20-1-status',
    '/phase20-1-test',
    '/phase20-2-guard-status',
    '/phase20-2-ready',
    '/phase20-2-status',
    '/phase20-2-test',
    '/phase20-3-guard-status',
    '/phase20-3-ready',
    '/phase20-3-status',
    '/phase20-3-test',
    '/phase20-4-guard-status',
    '/phase20-4-ready',
    '/phase20-4-status',
    '/phase20-4-test',
    '/phase20-5-guard-status',
    '/phase20-5-ready',
    '/phase20-5-status',
    '/phase20-5-test',
    '/phase20-ready',
    '/phase20-status',
    '/phase21-1-guard-status',
    '/phase21-1-ready',
    '/phase21-1-status',
    '/phase21-1-test',
    '/phase21-2-guard-status',
    '/phase21-2-ready',
    '/phase21-2-status',
    '/phase21-2-test',
    '/phase21-3-guard-status',
    '/phase21-3-ready',
    '/phase21-3-status',
    '/phase21-3-test',
    '/phase21-4-guard-status',
    '/phase21-4-ready',
    '/phase21-4-status',
    '/phase21-4-test',
    '/phase21-5-guard-status',
    '/phase21-5-ready',
    '/phase21-5-status',
    '/phase21-5-test',
    '/phase21-ready',
    '/phase21-status',
    '/phase22-1-guard-status',
    '/phase22-1-ready',
    '/phase22-1-status',
    '/phase22-1-test',
    '/phase22-2-guard-status',
    '/phase22-2-ready',
    '/phase22-2-status',
    '/phase22-2-test',
    '/phase22-3-guard-status',
    '/phase22-3-ready',
    '/phase22-3-status',
    '/phase22-3-test',
    '/phase22-4-guard-status',
    '/phase22-4-ready',
    '/phase22-4-status',
    '/phase22-4-test',
    '/phase22-5-guard-status',
    '/phase22-5-ready',
    '/phase22-5-status',
    '/phase22-5-test',
    '/phase22-ready',
    '/phase22-status',
    '/phase23-1-guard-status',
    '/phase23-1-ready',
    '/phase23-1-status',
    '/phase23-1-test',
    '/phase23-2-guard-status',
    '/phase23-2-ready',
    '/phase23-2-status',
    '/phase23-2-test',
    '/phase23-3-guard-status',
    '/phase23-3-ready',
    '/phase23-3-status',
    '/phase23-3-test',
    '/phase23-4-guard-status',
    '/phase23-4-ready',
    '/phase23-4-status',
    '/phase23-4-test',
    '/phase23-5-guard-status',
    '/phase23-5-ready',
    '/phase23-5-status',
    '/phase23-5-test',
    '/phase23-ready',
    '/phase23-status',
    '/phase24-1-guard-status',
    '/phase24-1-ready',
    '/phase24-1-status',
    '/phase24-1-test',
    '/phase24-2-guard-status',
    '/phase24-2-ready',
    '/phase24-2-status',
    '/phase24-2-test',
    '/phase24-3-guard-status',
    '/phase24-3-ready',
    '/phase24-3-status',
    '/phase24-3-test',
    '/phase24-4-guard-status',
    '/phase24-4-ready',
    '/phase24-4-status',
    '/phase24-4-test',
    '/phase24-5-guard-status',
    '/phase24-5-ready',
    '/phase24-5-status',
    '/phase24-5-test',
    '/phase24-ready',
    '/phase24-status',
    '/phase25-1-guard-status',
    '/phase25-1-ready',
    '/phase25-1-status',
    '/phase25-1-test',
    '/phase25-2-guard-status',
    '/phase25-2-ready',
    '/phase25-2-status',
    '/phase25-2-test',
    '/phase5-status',
    '/phase6-ready',
    '/phase6-status',
    '/reply-bridge-guard-status',
    '/reply-bridge-status',
    '/reply-bridge-test',
    '/reply-cooldown-guard-status',
    '/reply-cooldown-status',
    '/reply-cooldown-test',
    '/speech-dispatch-guard-status',
    '/speech-dispatch-status',
    '/speech-dispatch-test',
    '/stream-pilot-control-guard-status',
    '/stream-pilot-control-status',
    '/stream-pilot-control-test',
    '/stream-pilot-enable-guard-status',
    '/stream-pilot-enable-status',
    '/stream-pilot-enable-test',
    '/stream-rollback-guard-status',
    '/stream-rollback-status',
    '/stream-rollback-test',
    '/voice-binding-guard-status',
    '/voice-binding-status',
    '/voice-binding-test',
    '/voice-dispatch-guard-status',
    '/voice-dispatch-status',
    '/voice-dispatch-test',
    '/voice-engine-impl-guard-status',
    '/voice-engine-impl-status',
    '/voice-engine-impl-test',
    '/voice-engine-patch-guard-status',
    '/voice-engine-patch-status',
    '/voice-engine-patch-test',
    '/voice-gate-guard-status',
    '/voice-gate-status',
    '/voice-gate-test',
    '/voice-latency-baseline-guard-status',
    '/voice-latency-baseline-status',
    '/voice-latency-baseline-test',
    '/voice-latency-design-guard-status',
    '/voice-latency-design-status',
    '/voice-latency-design-test',
    '/voice-latency-gate-guard-status',
    '/voice-latency-gate-status',
    '/voice-latency-gate-test',
    '/voice-stream-gate-guard-status',
    '/voice-stream-gate-status',
    '/voice-stream-gate-test',
    '/voice-stream-safety-guard-status',
    '/voice-stream-safety-status',
    '/voice-stream-safety-test',
    '/voice-streaming-decision-guard-status',
    '/voice-streaming-decision-status',
    '/voice-streaming-decision-test',
    '/voice-streaming-dry-run-guard-status',
    '/voice-streaming-dry-run-status',
    '/voice-streaming-dry-run-test',
    '/voice-telemetry-guard-status',
    '/voice-telemetry-status',
    '/voice-telemetry-test',
})

_PHASE_COMPAT_PREFIX_COMMANDS = (
    '/controlled-stream-gate-test ',
    '/controlled-stream-pilot-test ',
    '/direct-voice-pilot-test ',
    '/expression-dispatch-test ',
    '/guarded-stream-call-test ',
    '/guarded-voice-dispatch-test ',
    '/live-path-replacement-test ',
    '/live-reply-gate-test ',
    '/live-reply-test ',
    '/live-speech-safety-test ',
    '/live-stream-measurement-test ',
    '/live-voice-control-test ',
    '/live-voice-gate-test ',
    '/phase19-1-test ',
    '/phase19-2-test ',
    '/phase19-3-test ',
    '/phase19-4-test ',
    '/phase19-5-test ',
    '/phase20-1-test ',
    '/phase20-2-test ',
    '/phase20-3-test ',
    '/phase20-4-test ',
    '/phase20-5-test ',
    '/phase21-1-test ',
    '/phase21-2-test ',
    '/phase21-3-test ',
    '/phase21-4-test ',
    '/phase21-5-test ',
    '/phase22-1-test ',
    '/phase22-2-test ',
    '/phase22-3-test ',
    '/phase22-4-test ',
    '/phase22-5-test ',
    '/phase23-1-test ',
    '/phase23-2-test ',
    '/phase23-3-test ',
    '/phase23-4-test ',
    '/phase23-5-test ',
    '/phase24-1-test ',
    '/phase24-2-test ',
    '/phase24-3-test ',
    '/phase24-4-test ',
    '/phase24-5-test ',
    '/phase25-1-test ',
    '/phase25-2-test ',
    '/reply-bridge-test ',
    '/reply-cooldown-test ',
    '/speech-dispatch-test ',
    '/stream-pilot-control-test ',
    '/stream-pilot-enable-test ',
    '/stream-rollback-test ',
    '/voice-binding-test ',
    '/voice-dispatch-test ',
    '/voice-engine-impl-test ',
    '/voice-engine-patch-test ',
    '/voice-gate-test ',
    '/voice-latency-baseline-test ',
    '/voice-latency-design-test ',
    '/voice-latency-gate-test ',
    '/voice-stream-gate-test ',
    '/voice-stream-safety-test ',
    '/voice-streaming-decision-test ',
    '/voice-streaming-dry-run-test ',
    '/voice-telemetry-test ',
)


def _is_generated_final_phase_command(text_lower: str) -> bool:
    for phase in range(26, 33):
        if text_lower in {
            f"/phase{phase}-status",
            f"/p{phase}",
            f"/phase{phase}-guard-status",
            f"/phase{phase}-test",
            f"/phase{phase}-ready",
            f"/p{phase}-ready",
        }:
            return True
        if text_lower.startswith(f"/phase{phase}-test "):
            return True
    return False


def is_phase_compat_command(text_lower: str) -> bool:
    return (
        text_lower in _PHASE_COMPAT_EXACT_COMMANDS
        or any(text_lower.startswith(prefix) for prefix in _PHASE_COMPAT_PREFIX_COMMANDS)
        or _is_generated_final_phase_command(text_lower)
    )


__all__ = ["is_phase_compat_command"]
