<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>NanaBridge</AssemblyName>
    <RootNamespace>NanaBridge</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="StardewModdingAPI">
      <HintPath>$(StardewGamePath)\StardewModdingAPI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Stardew Valley">
      <HintPath>$(StardewGamePath)\Stardew Valley.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="StardewValley.GameData">
      <HintPath>$(StardewGamePath)\StardewValley.GameData.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="MonoGame.Framework">
      <HintPath>$(StardewGamePath)\MonoGame.Framework.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="xTile">
      <HintPath>$(StardewGamePath)\xTile.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
