"""Help output — phase state and command help summaries."""


def print_phase3_state():
    # NOTE: browser access removed — these helpers only print static text.
    # Dynamic browser state (browser dict, age, fresh, cdp_state, page_heading, etc.)
    # should be injected by the caller if needed.
    print("🧭 Phase 3 Browser")
    print("  Snapshot: Fresh=Unknown | Age=Unknown | MaxAge=Unknown")
    print("  Page: Kind=Unknown | Title=Unknown")
    print("  URL: Unknown")
    print("  Heading: Unknown")
    print("  Selected: Unknown")
    print("  DOM debug: Unknown")
    print("  Guardrail: read-only; no click/type/navigate actions")
    print("  Commands: /browser | /br | /br-deep | /browser-refresh | /dom | /focus")


def print_phase4_state():
    print("🧭 Phase 4 Foundation")
    print("  Queue: P0 user input > P1 proactive > P2 background")
    print("  Actions: registry + broker + pending confirmation")
    print("  Guardrail: brain suggests, broker validates, Ba confirms later")
    print("  Commands: /queue | /actions | /broker-test | /action-propose | /pending-action")
    print("  Plan: /action-plan | /suggest")
    print("  Pillar 0: /privacy-test | /context-preview")
    print("  Sidecar router: /route-test <text>")
    print("  LLMGate sidecar: /llmgate-test <text>")
    print("  Intent planner: /intent-test <text>")
    print("  Social policy: /social-policy")
    print("  Social draft: /social-target | /social-classify | /social-draft-test <text>")
    print("  Social draft + vision: /social-draft-vision <text>")
    print("  Vision preview: /vision-preview | /vision-describe")
    print("  Draft queue: /drafts | /draft-show <id> | /draft-confirm <id> | /draft-cancel <id>")
    print("  Persona governor: /vibe-status | /state-log | /reset-vibe | /focus-mode | /technical-mode | /social-mode | /chill-mode")
    print("  Residue: /residue-status | /residue")
    print("  Presence rhythm: /presence | /presence-on | /presence-off | /presence-reset")
    print("  Attention window: /attention")
    print("  Recovery: /recovery | /recovery-clear")
    print("  Runtime dashboard: /nana-status | /ns | /phase5-status")
    print("  Refiner sidecar: /refine-test <draft>")
    print("  Refiner guard: /refine-guard-test <draft>")
    print("  Refiner auto-test: /refine-auto-test <draft>")
    print("  Confirm: /action-confirm <id> | /action-cancel <id>")
    print("  Debug only: /broker-test-edge | /action-propose-edge")
    print("  Real executor: browser.scroll only")


def print_command_help():
    print("🧭 Nana Commands")
    print("  Nana Web: /web (ensure local app, then open Microsoft Edge)")
    print("  Core: /status | /stage-status | /stage-output-status | /voice-status | /voice-inline-tag-status | /voice-inline-tag-preview <text> | /voice-delivery-status | /voice-delivery-preview <text> | /voice-span-status | /voice-span-preview <text> | /voice-budget-status | /voice-budget-preview <text> | /subtitle-status | /persona-boundary-status | /core-self-status | /core-self-preview [lane] | /core-self-test <prompt>|<reply> | /core-drift-status | /core-drift-preview <reply1 || prompt|reply2> | /core-anchor-status | /core-anchor-preview <prompt>|<reply> | /public-voice-status | /public-voice-preview | /public-voice-test <prompt>|<reply> | /public-conversation-status | /public-conversation-preview <text> | /public-thread-memory-status | /public-thread-memory-preview <text> | /public-joke-bank-status | /public-joke-bank-preview <text> | /public-viewer-memory-status | /public-viewer-memory-preview <viewer>|<text> | /public-scene-status | /public-scene-preview <text> | /public-quiet-room-status | /public-quiet-room-preview <text> | /public-fluency-status | /public-fluency-preview <text> | /public-reply-eval-status | /public-reply-eval-preview <prompt>|<reply> | /public-reply-feedback-status | /public-reply-feedback-preview <text> | /public-fallback-recovery-status | /public-fallback-recovery-preview <text> | /public-memory-filter-status | /public-memory-filter-preview <text> | /persona-spine-status | /mood-status | /mood-preview [lane] | /intention-status | /intention-preview | /session-review-status | /session-review-preview | /post-stream-review-status | /post-stream-review | /post-stream-lessons-status | /post-stream-recommendations | /post-stream-approve <id> | /post-stream-reject <id> | /post-stream-undo <lesson_id> | /lesson-history | /lesson-stale | /lane-affect-status | /lane-leak-audit | /memory-consolidation-preview | /context-budget-audit [lane] | /llm-route-status | /runtime-status | /nana-status | /ns | /help")
    print("  Viewer chat: /viewer-chat-status | /social-session-status | /viewer-chat-test <name>|<text> | /viewer-chat-clear")
    print("  Discord bridge: /discord-core-status | /discord-core-test <name>|<text>")
    print("  Presence node: /presence-node-status | /presence-node-diagnostics | /presence-session-status | /presence-session-diagnostics | /presence-camera-snapshot | /presence-stream-tone | /presence-voice-stress [240-1500]")
    print("  Stream stage: /stream-ready-status | /stream-event-log | /stream-status | /stream-policy-preview | /stream-live-on | /stream-live-off | /stream-break | /stream-resume | /proactive-stage-status | /proactive-stage-preview | /avatar-director-status | /avatar-director-preview [event] | /avatar-reaction-status | /avatar-reaction-preview [event] | /public-avatar-status | /public-avatar-preview <text>|<reply> | /avatar-reaction-apply-preview [event] | /avatar-runtime-status | /avatar-runtime-look-preview [left|right|center|up|down] | /avatar-runtime-look [left|right|center|up|down] | /avatar-runtime-preview [action] | /avatar-runtime-start | /avatar-runtime-stop | /avatar-runtime-submit [action] | /avatar-vts-status | /avatar-vts-enable | /avatar-vts-disable | /avatar-vts-preview [event] | /avatar-vts-dispatch [event] | /avatar-event-status | /avatar-event-preview | /avatar-event-test <text> | /avatar-live-hook-status | /avatar-live-hook-preview | /avatar-live-hook-plan | /starter-proposals | /starter-proposal-preview | /starter-proposal-create | /starter-proposal-approve <id> | /starter-proposal-send <id> | /starter-send-status | /starter-send-enable | /starter-send-disable | /starter-auto-status | /starter-auto-enable | /starter-auto-disable | /starter-auto-preview | /starter-auto-tick | /starter-auto-worker-start | /starter-auto-worker-stop | /starter-proposal-cancel <id> | /starter-proposal-clear")
    print("  Awareness: /awareness-status | /awareness-memory-status | /br | /br-deep | /browser | /dom")
    print("  Context: /video-context | /context-confidence | /context-priority | /context-recovery | /context-preview | /evidence-trace")
    print("  Reconcile: /reconcile | /runtime-reconcile | /reconcile-status | /reconcile-check | /reconcile-expect <expected>|<sample>||<vision>")
    print("  Memory: /memory-status | /memory-grounding-status | /memory-search <text> | /memory-export | /memory-review | /memory-compact-preview | /memory-action")
    print("  Dialogue: /vibe-status | /residue | /reset-vibe | /focus-mode | /technical-mode | /social-mode | /chill-mode")
    print("  Presence: /presence | /presence-on | /presence-off | /presence-reset | /attention")
    print("  Autonomy: /autonomy-status | /autonomy-pause | /autonomy-resume | /autonomy-mode <ultra-short|full>")
    print("  Actions: /actions | /broker-test <action> | /action-propose <action> | /pending-action | /action-plan")
    print("  Action confirm: /action-confirm <id> | /action-cancel <id> | /suggest")
    print("  Social read/draft: /social-target | /social-classify <text> | /social-policy | /social-guard-status | /social-draft-test <text>")
    print("  Drafts: /drafts | /draft-show <id> | /draft-quality | /draft-confirm <id> | /draft-cancel <id>")
    print("  Vision: /vision-preview | /vision-describe | /vision-cache | /vision-cache-clear | /social-draft-vision <text>")
    print("  Diagnostics: /command-truth-status | /command-truth <cmd> | /command-route-test <cmd> | /llm-route-status | /llm-provider [llmgate|openai_direct [model] [effort]] | /interaction-latency-status | /llm-route-probe [model] [text] | /llm-route-bakeoff [text] | /llmgate-test <text> | /route-test <text> | /intent-test <text> | /speech-shape-test <text>")
    print("  Debug maps: /phase3 | /phase4")
    print("  Archived: old phase/voice telemetry commands are hidden from help and fail closed if called directly.")
